version: '2'
services:
    jtaxiiserver-app:
        image: jtaxiiserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jtaxiiserver-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=JTaxiiServer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jtaxiiserver-mongodb:
        extends:
            file: mongodb.yml
            service: jtaxiiserver-mongodb
